### ISSUE TITLE
Feature request : More Filters

### ISSUE THREAD

**Issue by KelvinPac** [suiko1984/geofirestore-android#1]
Cheers for this awesome library, I have already tried it and it was awesome. I am storing the geofirestore locations on the same collection so doing a query will return me the document snapshots. Is there a way to limit the results just like in Firestore? And is there a way I would pass another Firestore query to geofirestore so that it would also order the results or sort them in a certain way using the other database fields just as we can do in Firestore.
Thanks.

**Comment by suiko1984** [comment]
Thank you @KelvinPac 
An update of this library would contain your suggested features.

**Comment by KelvinPac** [comment]
Is there a timeline of when to expect this?

**Comment by mikeborodin** [comment]
Wow! Cool stuff, also interested in more filters feature!

**Comment by suiko1984** [comment]
Hi guys, compound queries have been added to this new 1.1.0 version!
Please read this link before using it: https://github.com/suiko1984/geofirestore-android#compound-query

Enjoy!
