### ISSUE TITLE
How to use setCenter and setRadius

### ISSUE THREAD

**Issue by zoro238** [suiko1984/geofirestore-android#10]
A possible example explains how to use the method setCenter and setRadius
Because I want him to give us near within 10 kilometers

**Comment by zoro238** [comment]
and explains 

\\
Updating the query criteria

The GeoQuery search area can be changed with setCenter and setRadius. Key exited and key entered events will be fired for keys moving in and out of the old and new search area, respectively. No key moved events will be fired; however, key moved events might occur independently.

Updating the search area can be helpful in cases such as when you need to update the query to the new visible map area after a user scrolls.

**Comment by suiko1984** [comment]
Hi @zoro238 , thanks for the suggestion. I will add your description in the next update :)

**Comment by zoro238** [comment]
thank you ,I hope you add
How do I know how many people are in range?
And when the next update .. Thank you for your patience and speed of your response
