### ISSUE TITLE
getAtLocation wrong results

### ISSUE THREAD

**Issue by dmitriysierov** [suiko1984/geofirestore-android#13]
radius is inaccurate. A query of 15 kilometers yields results of 25 kilometers and above

**Comment by dmitriysierov** [comment]
center (49.9470, 36.1527) result (49.738972, 36.043528)

**Comment by suiko1984** [comment]
Thank you for the notice.
A fix is being published now, you should update the dependencies to 1.2.2. It can take several hours before it is available.
