### ISSUE TITLE
Feature request : More Filters

### ISSUE THREAD

**Issue by KelvinPac** [suiko1984/geofirestore-android#2]
With the current setup I found the library using, if am storing the geofirestore locations on the same collection as my documents, doing a query will return all documents which match, but on large collections the results may be huge. Will we be seeing some kind of pagination or something similar soon? . Am already using this awesome lib in production

**Comment by suiko1984** [comment]
Thank you @KelvinPac 
An update of this library would contain your suggested features.

**Comment by suiko1984** [comment]
Hi, compound queries have been added to this new 1.1.0 version!
Please read this link before using it: https://github.com/suiko1984/geofirestore-android#compound-query
To solve your pagination problem, you can for instance use the "limit" query.
Enjoy!

**Comment by KelvinPac** [comment]
Thanks. I have updated to the new Library. Limits work well. I haven't figured out yet how pagination would work for example if I fetched the first 10 then wanted to fetch the next 10
**Cheers @suiko1984**
