### ISSUE TITLE
Having compatibility issues with other libraries 

### ISSUE THREAD

**Issue by scorlingonzalez** [suiko1984/geofirestore-android#6]
below are the libraries that i am trying to work with, I have some libraries there that cannot be upgraded in version as they don't play nice with each other. when I add this library I get the following error:
error: cannot access zzbgl
class file for com.google.android.gms.internal.zzbgl not found

this has to do with firebase auth. I have read that I have to increase the auth version but then I would have to increase every other library therefor making the problem worse. 
   
here is a list of the apis i need to work together:
 implementation 'com.google.code.gson:gson:2.8.0'
    implementation 'com.google.android.gms:play-services:12.0.1'
    // fireBase
    implementation 'com.google.firebase:firebase-database:12.0.1'
    implementation 'com.google.firebase:firebase-auth:12.0.1'
    implementation 'com.google.firebase:firebase-firestore:12.0.1'
    implementation 'com.google.firebase:firebase-messaging:12.0.1'
    implementation 'com.google.firebase:firebase-storage:12.0.1'
    //fireBase geo location
    implementation 'com.koalap:geofirestore-android:1.1.0'
    //lowest version compatible
    implementation 'com.firebaseui:firebase-ui-database:3.1.0'
    implementation 'com.firebaseui:firebase-ui-storage:3.1.0'

**Comment by suiko1984** [comment]
My suggestion is that you upload all of your libraries to the latest version, including com.firebaseui:firebase-ui:
        implementation 'com.google.code.gson:gson:2.8.4'
        implementation 'com.google.firebase:firebase-database:16.0.6'
        implementation 'com.google.firebase:firebase-auth:16.1.0'
        implementation 'com.google.firebase:firebase-firestore:18.0.0'
        implementation 'com.google.firebase:firebase-messaging:17.3.4'
        implementation 'com.google.firebase:firebase-storage:16.0.5'
        implementation 'com.firebaseui:firebase-ui-database:4.3.1'
        implementation 'com.firebaseui:firebase-ui-storage:4.3.1'
