### ISSUE TITLE
No support for latest firestore 18.2.0 and 18.0.1

### ISSUE THREAD

**Issue by KelvinPac** [suiko1984/geofirestore-android#7]
Hi, can you please update the library to support new firestore library versions? I have seen no recent commits or releases in a while. Has support ended for this library?

**Comment by suiko1984** [comment]
Hi @KelvinPac I will update a new version very soon. Thanks!

**Comment by KelvinPac** [comment]
I am currently using the library as a module in the project which I added support for latest firestore
